#!/usr/bin/env python3
import os
import hashlib

def make_uuid(name):
    # Generates a valid 24-character hex PBX UUID
    h = hashlib.md5(name.encode('utf-8')).hexdigest()[:24].upper()
    return h

def main():
    base_dir = os.path.abspath("TikTokCleaner")
    proj_dir = os.path.join(base_dir, "TikTokCleaner.xcodeproj")
    os.makedirs(proj_dir, exist_ok=True)
    
    src_dir = os.path.join(base_dir, "TikTokCleaner")
    
    # Collect swift files
    app_swift_files = []
    test_swift_files = []
    resource_files = []
    
    for root, dirs, files in os.walk(src_dir):
        for f in files:
            rel_path = os.path.relpath(os.path.join(root, f), base_dir)
            if f.endswith(".swift"):
                if "Tests" in rel_path:
                    test_swift_files.append(rel_path)
                else:
                    app_swift_files.append(rel_path)
            elif f == "Assets.xcassets" or "Assets.xcassets" in rel_path:
                # We add the root xcassets
                xcassets_rel = "TikTokCleaner/Resources/Assets.xcassets"
                if xcassets_rel not in resource_files:
                    resource_files.append(xcassets_rel)
            elif f == "Info.plist":
                pass # referenced in build settings
            elif f.endswith(".entitlements"):
                pass # referenced in build settings
    
    # Sort files
    app_swift_files.sort()
    test_swift_files.sort()
    
    proj_uuid = make_uuid("TikTokCleaner_Project")
    main_group_uuid = make_uuid("MainGroup")
    products_group_uuid = make_uuid("ProductsGroup")
    app_target_uuid = make_uuid("AppTarget")
    test_target_uuid = make_uuid("TestTarget")
    
    app_product_uuid = make_uuid("TikTokCleaner.app")
    test_product_uuid = make_uuid("TikTokCleanerTests.xctest")
    
    app_sources_build_phase_uuid = make_uuid("AppSourcesBuildPhase")
    app_frameworks_build_phase_uuid = make_uuid("AppFrameworksBuildPhase")
    app_resources_build_phase_uuid = make_uuid("AppResourcesBuildPhase")
    
    test_sources_build_phase_uuid = make_uuid("TestSourcesBuildPhase")
    test_frameworks_build_phase_uuid = make_uuid("TestFrameworksBuildPhase")
    test_resources_build_phase_uuid = make_uuid("TestResourcesBuildPhase")
    
    container_item_proxy_uuid = make_uuid("ContainerItemProxy")
    target_dependency_uuid = make_uuid("TargetDependency")
    
    # Build configurations
    app_debug_config_uuid = make_uuid("AppDebugConfig")
    app_release_config_uuid = make_uuid("AppReleaseConfig")
    test_debug_config_uuid = make_uuid("TestDebugConfig")
    test_release_config_uuid = make_uuid("TestReleaseConfig")
    proj_debug_config_uuid = make_uuid("ProjDebugConfig")
    proj_release_config_uuid = make_uuid("ProjReleaseConfig")
    
    app_config_list_uuid = make_uuid("AppConfigList")
    test_config_list_uuid = make_uuid("TestConfigList")
    proj_config_list_uuid = make_uuid("ProjConfigList")
    
    pbx = []
    pbx.append("// !$*UTF8*$!")
    pbx.append("{")
    pbx.append("\tarchiveVersion = 1;")
    pbx.append("\tclasses = {")
    pbx.append("\t};")
    pbx.append("\tobjectVersion = 56;")
    pbx.append("\tobjects = {")
    
    # 1. PBXBuildFile
    pbx.append("\n/* Begin PBXBuildFile section */")
    for f in app_swift_files:
        bf_uuid = make_uuid(f + "_buildfile")
        fr_uuid = make_uuid(f + "_fileref")
        fname = os.path.basename(f)
        pbx.append(f"\t\t{bf_uuid} /* {fname} in Sources */ = {{isa = PBXBuildFile; fileRef = {fr_uuid} /* {fname} */; }};")
    
    for f in test_swift_files:
        bf_uuid = make_uuid(f + "_buildfile")
        fr_uuid = make_uuid(f + "_fileref")
        fname = os.path.basename(f)
        pbx.append(f"\t\t{bf_uuid} /* {fname} in Sources */ = {{isa = PBXBuildFile; fileRef = {fr_uuid} /* {fname} */; }};")
        
    for f in resource_files:
        bf_uuid = make_uuid(f + "_buildfile")
        fr_uuid = make_uuid(f + "_fileref")
        fname = os.path.basename(f)
        pbx.append(f"\t\t{bf_uuid} /* {fname} in Resources */ = {{isa = PBXBuildFile; fileRef = {fr_uuid} /* {fname} */; }};")
    pbx.append("/* End PBXBuildFile section */\n")
    
    # 2. PBXContainerItemProxy
    pbx.append("/* Begin PBXContainerItemProxy section */")
    pbx.append(f"\t\t{container_item_proxy_uuid} /* PBXContainerItemProxy */ = {{")
    pbx.append("\t\t\tisa = PBXContainerItemProxy;")
    pbx.append(f"\t\t\tcontainerPortal = {proj_uuid} /* Project object */;")
    pbx.append("\t\t\tproxyType = 1;")
    pbx.append(f"\t\t\tremoteGlobalIDString = {app_target_uuid};")
    pbx.append("\t\t\tremoteInfo = TikTokCleaner;")
    pbx.append("\t\t};")
    pbx.append("/* End PBXContainerItemProxy section */\n")
    
    # 3. PBXFileReference
    pbx.append("/* Begin PBXFileReference section */")
    pbx.append(f"\t\t{app_product_uuid} /* TikTokCleaner.app */ = {{isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = TikTokCleaner.app; sourceTree = BUILT_PRODUCTS_DIR; }};")
    pbx.append(f"\t\t{test_product_uuid} /* TikTokCleanerTests.xctest */ = {{isa = PBXFileReference; explicitFileType = wrapper.cfbundle; includeInIndex = 0; path = TikTokCleanerTests.xctest; sourceTree = BUILT_PRODUCTS_DIR; }};")
    
    all_files = app_swift_files + test_swift_files + resource_files
    for f in all_files:
        fr_uuid = make_uuid(f + "_fileref")
        fname = os.path.basename(f)
        if f.endswith(".swift"):
            pbx.append(f"\t\t{fr_uuid} /* {fname} */ = {{isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = \"{f}\"; sourceTree = \"<group>\"; }};")
        elif f.endswith(".xcassets"):
            pbx.append(f"\t\t{fr_uuid} /* {fname} */ = {{isa = PBXFileReference; lastKnownFileType = folder.assetcatalog; path = \"{f}\"; sourceTree = \"<group>\"; }};")
    pbx.append("/* End PBXFileReference section */\n")
    
    # 4. PBXFrameworksBuildPhase
    pbx.append("/* Begin PBXFrameworksBuildPhase section */")
    pbx.append(f"\t\t{app_frameworks_build_phase_uuid} /* Frameworks */ = {{")
    pbx.append("\t\t\tisa = PBXFrameworksBuildPhase;")
    pbx.append("\t\t\tbuildActionMask = 2147483647;")
    pbx.append("\t\t\tfiles = (")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\trunOnlyForDeploymentPostprocessing = 0;")
    pbx.append("\t\t};")
    
    pbx.append(f"\t\t{test_frameworks_build_phase_uuid} /* Frameworks */ = {{")
    pbx.append("\t\t\tisa = PBXFrameworksBuildPhase;")
    pbx.append("\t\t\tbuildActionMask = 2147483647;")
    pbx.append("\t\t\tfiles = (")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\trunOnlyForDeploymentPostprocessing = 0;")
    pbx.append("\t\t};")
    pbx.append("/* End PBXFrameworksBuildPhase section */\n")
    
    # 5. PBXGroup
    pbx.append("/* Begin PBXGroup section */")
    pbx.append(f"\t\t{main_group_uuid} = {{")
    pbx.append("\t\t\tisa = PBXGroup;")
    pbx.append("\t\t\tchildren = (")
    for f in all_files:
        fr_uuid = make_uuid(f + "_fileref")
        fname = os.path.basename(f)
        pbx.append(f"\t\t\t\t{fr_uuid} /* {fname} */,")
    pbx.append(f"\t\t\t\t{products_group_uuid} /* Products */,")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\tsourceTree = \"<group>\";")
    pbx.append("\t\t};")
    
    pbx.append(f"\t\t{products_group_uuid} /* Products */ = {{")
    pbx.append("\t\t\tisa = PBXGroup;")
    pbx.append("\t\t\tchildren = (")
    pbx.append(f"\t\t\t\t{app_product_uuid} /* TikTokCleaner.app */,")
    pbx.append(f"\t\t\t\t{test_product_uuid} /* TikTokCleanerTests.xctest */,")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\tname = Products;")
    pbx.append("\t\t\tsourceTree = \"<group>\";")
    pbx.append("\t\t};")
    pbx.append("/* End PBXGroup section */\n")
    
    # 6. PBXNativeTarget
    pbx.append("/* Begin PBXNativeTarget section */")
    pbx.append(f"\t\t{app_target_uuid} /* TikTokCleaner */ = {{")
    pbx.append("\t\t\tisa = PBXNativeTarget;")
    pbx.append(f"\t\t\tbuildConfigurationList = {app_config_list_uuid} /* Build configuration list for PBXNativeTarget \"TikTokCleaner\" */;")
    pbx.append("\t\t\tbuildPhases = (")
    pbx.append(f"\t\t\t\t{app_sources_build_phase_uuid} /* Sources */,")
    pbx.append(f"\t\t\t\t{app_frameworks_build_phase_uuid} /* Frameworks */,")
    pbx.append(f"\t\t\t\t{app_resources_build_phase_uuid} /* Resources */,")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\tbuildRules = (")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\tdependencies = (")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\tname = TikTokCleaner;")
    pbx.append("\t\t\tproductName = TikTokCleaner;")
    pbx.append(f"\t\t\tproductReference = {app_product_uuid} /* TikTokCleaner.app */;")
    pbx.append("\t\t\tproductType = \"com.apple.product-type.application\";")
    pbx.append("\t\t};")
    
    pbx.append(f"\t\t{test_target_uuid} /* TikTokCleanerTests */ = {{")
    pbx.append("\t\t\tisa = PBXNativeTarget;")
    pbx.append(f"\t\t\tbuildConfigurationList = {test_config_list_uuid} /* Build configuration list for PBXNativeTarget \"TikTokCleanerTests\" */;")
    pbx.append("\t\t\tbuildPhases = (")
    pbx.append(f"\t\t\t\t{test_sources_build_phase_uuid} /* Sources */,")
    pbx.append(f"\t\t\t\t{test_frameworks_build_phase_uuid} /* Frameworks */,")
    pbx.append(f"\t\t\t\t{test_resources_build_phase_uuid} /* Resources */,")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\tbuildRules = (")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\tdependencies = (")
    pbx.append(f"\t\t\t\t{target_dependency_uuid} /* PBXTargetDependency */,")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\tname = TikTokCleanerTests;")
    pbx.append("\t\t\tproductName = TikTokCleanerTests;")
    pbx.append(f"\t\t\tproductReference = {test_product_uuid} /* TikTokCleanerTests.xctest */;")
    pbx.append("\t\t\tproductType = \"com.apple.product-type.bundle.unit-test\";")
    pbx.append("\t\t};")
    pbx.append("/* End PBXNativeTarget section */\n")
    
    # 7. PBXProject
    pbx.append("/* Begin PBXProject section */")
    pbx.append(f"\t\t{proj_uuid} /* Project object */ = {{")
    pbx.append("\t\t\tisa = PBXProject;")
    pbx.append("\t\t\tattributes = {")
    pbx.append("\t\t\t\tBuildIndependentTargetsInParallel = 1;")
    pbx.append("\t\t\t\tLastSwiftUpdateCheck = 1530;")
    pbx.append("\t\t\t\tLastUpgradeCheck = 1530;")
    pbx.append("\t\t\t\tTargetAttributes = {")
    pbx.append(f"\t\t\t\t\t{app_target_uuid} = {{")
    pbx.append("\t\t\t\t\t\tCreatedOnToolsVersion = 15.3;")
    pbx.append("\t\t\t\t\t};")
    pbx.append(f"\t\t\t\t\t{test_target_uuid} = {{")
    pbx.append("\t\t\t\t\t\tCreatedOnToolsVersion = 15.3;")
    pbx.append(f"\t\t\t\t\t\tTestTargetID = {app_target_uuid};")
    pbx.append("\t\t\t\t\t};")
    pbx.append("\t\t\t\t};")
    pbx.append("\t\t\t};")
    pbx.append(f"\t\t\tbuildConfigurationList = {proj_config_list_uuid} /* Build configuration list for PBXProject \"TikTokCleaner\" */;")
    pbx.append("\t\t\tcompatibilityVersion = \"Xcode 14.0\";")
    pbx.append("\t\t\tdevelopmentRegion = fr;")
    pbx.append("\t\t\thasScannedForEncodings = 0;")
    pbx.append("\t\t\tknownRegions = (")
    pbx.append("\t\t\t\ten,")
    pbx.append("\t\t\t\tfr,")
    pbx.append("\t\t\t\tBase,")
    pbx.append("\t\t\t);")
    pbx.append(f"\t\t\tmainGroup = {main_group_uuid};")
    pbx.append(f"\t\t\tproductRefGroup = {products_group_uuid} /* Products */;")
    pbx.append("\t\t\tprojectDirPath = \"\";")
    pbx.append("\t\t\tprojectRoot = \"\";")
    pbx.append("\t\t\ttargets = (")
    pbx.append(f"\t\t\t\t{app_target_uuid} /* TikTokCleaner */,")
    pbx.append(f"\t\t\t\t{test_target_uuid} /* TikTokCleanerTests */,")
    pbx.append("\t\t\t);")
    pbx.append("\t\t};")
    pbx.append("/* End PBXProject section */\n")
    
    # 8. PBXResourcesBuildPhase
    pbx.append("/* Begin PBXResourcesBuildPhase section */")
    pbx.append(f"\t\t{app_resources_build_phase_uuid} /* Resources */ = {{")
    pbx.append("\t\t\tisa = PBXResourcesBuildPhase;")
    pbx.append("\t\t\tbuildActionMask = 2147483647;")
    pbx.append("\t\t\tfiles = (")
    for f in resource_files:
        bf_uuid = make_uuid(f + "_buildfile")
        fname = os.path.basename(f)
        pbx.append(f"\t\t\t\t{bf_uuid} /* {fname} in Resources */,")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\trunOnlyForDeploymentPostprocessing = 0;")
    pbx.append("\t\t};")
    
    pbx.append(f"\t\t{test_resources_build_phase_uuid} /* Resources */ = {{")
    pbx.append("\t\t\tisa = PBXResourcesBuildPhase;")
    pbx.append("\t\t\tbuildActionMask = 2147483647;")
    pbx.append("\t\t\tfiles = (")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\trunOnlyForDeploymentPostprocessing = 0;")
    pbx.append("\t\t};")
    pbx.append("/* End PBXResourcesBuildPhase section */\n")
    
    # 9. PBXSourcesBuildPhase
    pbx.append("/* Begin PBXSourcesBuildPhase section */")
    pbx.append(f"\t\t{app_sources_build_phase_uuid} /* Sources */ = {{")
    pbx.append("\t\t\tisa = PBXSourcesBuildPhase;")
    pbx.append("\t\t\tbuildActionMask = 2147483647;")
    pbx.append("\t\t\tfiles = (")
    for f in app_swift_files:
        bf_uuid = make_uuid(f + "_buildfile")
        fname = os.path.basename(f)
        pbx.append(f"\t\t\t\t{bf_uuid} /* {fname} in Sources */,")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\trunOnlyForDeploymentPostprocessing = 0;")
    pbx.append("\t\t};")
    
    pbx.append(f"\t\t{test_sources_build_phase_uuid} /* Sources */ = {{")
    pbx.append("\t\t\tisa = PBXSourcesBuildPhase;")
    pbx.append("\t\t\tbuildActionMask = 2147483647;")
    pbx.append("\t\t\tfiles = (")
    for f in test_swift_files:
        bf_uuid = make_uuid(f + "_buildfile")
        fname = os.path.basename(f)
        pbx.append(f"\t\t\t\t{bf_uuid} /* {fname} in Sources */,")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\trunOnlyForDeploymentPostprocessing = 0;")
    pbx.append("\t\t};")
    pbx.append("/* End PBXSourcesBuildPhase section */\n")
    
    # 10. PBXTargetDependency
    pbx.append("/* Begin PBXTargetDependency section */")
    pbx.append(f"\t\t{target_dependency_uuid} /* PBXTargetDependency */ = {{")
    pbx.append("\t\t\tisa = PBXTargetDependency;")
    pbx.append(f"\t\t\ttarget = {app_target_uuid} /* TikTokCleaner */;")
    pbx.append(f"\t\t\ttargetProxy = {container_item_proxy_uuid} /* PBXContainerItemProxy */;")
    pbx.append("\t\t};")
    pbx.append("/* End PBXTargetDependency section */\n")
    
    # 11. XCBuildConfiguration
    pbx.append("/* Begin XCBuildConfiguration section */")
    pbx.append(f"\t\t{proj_debug_config_uuid} /* Debug */ = {{")
    pbx.append("\t\t\tisa = XCBuildConfiguration;")
    pbx.append("\t\t\tbuildSettings = {")
    pbx.append("\t\t\t\tALWAYS_SEARCH_USER_PATHS = NO;")
    pbx.append("\t\t\t\tCLANG_ANALYZER_NONNULL = YES;")
    pbx.append("\t\t\t\tCLANG_CXX_LANGUAGE_STANDARD = \"gnu++20\";")
    pbx.append("\t\t\t\tCLANG_ENABLE_MODULES = YES;")
    pbx.append("\t\t\t\tCLANG_ENABLE_OBJC_ARC = YES;")
    pbx.append("\t\t\t\tCOPY_PHASE_STRIP = NO;")
    pbx.append("\t\t\t\tDEBUG_INFORMATION_FORMAT = dwarf;")
    pbx.append("\t\t\t\tENABLE_STRICT_OBJC_MSGSEND = YES;")
    pbx.append("\t\t\t\tENABLE_TESTABILITY = YES;")
    pbx.append("\t\t\t\tGCC_DYNAMIC_NO_PIC = NO;")
    pbx.append("\t\t\t\tGCC_OPTIMIZATION_LEVEL = 0;")
    pbx.append("\t\t\t\tGCC_PREPROCESSOR_DEFINITIONS = (")
    pbx.append("\t\t\t\t\t\"DEBUG=1\",")
    pbx.append("\t\t\t\t\t\"$(inherited)\",")
    pbx.append("\t\t\t\t);")
    pbx.append("\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = 16.0;")
    pbx.append("\t\t\t\tMTL_ENABLE_DEBUG_INFO = INCLUDE_SOURCE;")
    pbx.append("\t\t\t\tONLY_ACTIVE_ARCH = YES;")
    pbx.append("\t\t\t\tSDKROOT = iphoneos;")
    pbx.append("\t\t\t\tSWIFT_ACTIVE_COMPILATION_CONDITIONS = DEBUG;")
    pbx.append("\t\t\t\tSWIFT_OPTIMIZATION_LEVEL = \"-Onone\";")
    pbx.append("\t\t\t\tSWIFT_VERSION = 5.0;")
    pbx.append("\t\t\t};")
    pbx.append("\t\t\tname = Debug;")
    pbx.append("\t\t};")
    
    pbx.append(f"\t\t{proj_release_config_uuid} /* Release */ = {{")
    pbx.append("\t\t\tisa = XCBuildConfiguration;")
    pbx.append("\t\t\tbuildSettings = {")
    pbx.append("\t\t\t\tALWAYS_SEARCH_USER_PATHS = NO;")
    pbx.append("\t\t\t\tCLANG_ANALYZER_NONNULL = YES;")
    pbx.append("\t\t\t\tCLANG_CXX_LANGUAGE_STANDARD = \"gnu++20\";")
    pbx.append("\t\t\t\tCLANG_ENABLE_MODULES = YES;")
    pbx.append("\t\t\t\tCLANG_ENABLE_OBJC_ARC = YES;")
    pbx.append("\t\t\t\tCOPY_PHASE_STRIP = NO;")
    pbx.append("\t\t\t\tDEBUG_INFORMATION_FORMAT = \"dwarf-with-dsym\";")
    pbx.append("\t\t\t\tENABLE_NS_ASSERTIONS = NO;")
    pbx.append("\t\t\t\tENABLE_STRICT_OBJC_MSGSEND = YES;")
    pbx.append("\t\t\t\tGCC_OPTIMIZATION_LEVEL = s;")
    pbx.append("\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = 16.0;")
    pbx.append("\t\t\t\tMTL_ENABLE_DEBUG_INFO = NO;")
    pbx.append("\t\t\t\tSDKROOT = iphoneos;")
    pbx.append("\t\t\t\tSWIFT_COMPILATION_MODE = wholemodule;")
    pbx.append("\t\t\t\tSWIFT_OPTIMIZATION_LEVEL = \"-O\";")
    pbx.append("\t\t\t\tSWIFT_VERSION = 5.0;")
    pbx.append("\t\t\t\tVALIDATE_PRODUCT = YES;")
    pbx.append("\t\t\t};")
    pbx.append("\t\t\tname = Release;")
    pbx.append("\t\t};")
    
    pbx.append(f"\t\t{app_debug_config_uuid} /* Debug */ = {{")
    pbx.append("\t\t\tisa = XCBuildConfiguration;")
    pbx.append("\t\t\tbuildSettings = {")
    pbx.append("\t\t\t\tASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;")
    pbx.append("\t\t\t\tASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME = AccentColor;")
    pbx.append("\t\t\t\tCODE_SIGN_STYLE = Automatic;")
    pbx.append("\t\t\t\tCURRENT_PROJECT_VERSION = 1;")
    pbx.append("\t\t\t\tDEVELOPMENT_TEAM = \"\";")
    pbx.append("\t\t\t\tENABLE_PREVIEWS = YES;")
    pbx.append("\t\t\t\tGENERATE_INFOPLIST_FILE = NO;")
    pbx.append("\t\t\t\tINFOPLIST_FILE = TikTokCleaner/Resources/Info.plist;")
    pbx.append("\t\t\t\tLD_RUNPATH_SEARCH_PATHS = (")
    pbx.append("\t\t\t\t\t\"$(inherited)\",")
    pbx.append("\t\t\t\t\t\"@executable_path/Frameworks\",")
    pbx.append("\t\t\t\t);")
    pbx.append("\t\t\t\tMARKETING_VERSION = 1.0.0;")
    pbx.append("\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = com.tiktokcleaner.app;")
    pbx.append("\t\t\t\tPRODUCT_NAME = \"$(TARGET_NAME)\";")
    pbx.append("\t\t\t\tSWIFT_EMIT_LOC_STRINGS = YES;")
    pbx.append("\t\t\t\tSWIFT_VERSION = 5.0;")
    pbx.append("\t\t\t\tTARGETED_DEVICE_FAMILY = \"1,2\";")
    pbx.append("\t\t\t};")
    pbx.append("\t\t\tname = Debug;")
    pbx.append("\t\t};")
    
    pbx.append(f"\t\t{app_release_config_uuid} /* Release */ = {{")
    pbx.append("\t\t\tisa = XCBuildConfiguration;")
    pbx.append("\t\t\tbuildSettings = {")
    pbx.append("\t\t\t\tASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;")
    pbx.append("\t\t\t\tASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME = AccentColor;")
    pbx.append("\t\t\t\tCODE_SIGN_STYLE = Automatic;")
    pbx.append("\t\t\t\tCURRENT_PROJECT_VERSION = 1;")
    pbx.append("\t\t\t\tDEVELOPMENT_TEAM = \"\";")
    pbx.append("\t\t\t\tENABLE_PREVIEWS = YES;")
    pbx.append("\t\t\t\tGENERATE_INFOPLIST_FILE = NO;")
    pbx.append("\t\t\t\tINFOPLIST_FILE = TikTokCleaner/Resources/Info.plist;")
    pbx.append("\t\t\t\tLD_RUNPATH_SEARCH_PATHS = (")
    pbx.append("\t\t\t\t\t\"$(inherited)\",")
    pbx.append("\t\t\t\t\t\"@executable_path/Frameworks\",")
    pbx.append("\t\t\t\t);")
    pbx.append("\t\t\t\tMARKETING_VERSION = 1.0.0;")
    pbx.append("\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = com.tiktokcleaner.app;")
    pbx.append("\t\t\t\tPRODUCT_NAME = \"$(TARGET_NAME)\";")
    pbx.append("\t\t\t\tSWIFT_EMIT_LOC_STRINGS = YES;")
    pbx.append("\t\t\t\tSWIFT_VERSION = 5.0;")
    pbx.append("\t\t\t\tTARGETED_DEVICE_FAMILY = \"1,2\";")
    pbx.append("\t\t\t};")
    pbx.append("\t\t\tname = Release;")
    pbx.append("\t\t};")
    
    pbx.append(f"\t\t{test_debug_config_uuid} /* Debug */ = {{")
    pbx.append("\t\t\tisa = XCBuildConfiguration;")
    pbx.append("\t\t\tbuildSettings = {")
    pbx.append("\t\t\t\tBUNDLE_LOADER = \"$(TEST_HOST)\";")
    pbx.append("\t\t\t\tCODE_SIGN_STYLE = Automatic;")
    pbx.append("\t\t\t\tCURRENT_PROJECT_VERSION = 1;")
    pbx.append("\t\t\t\tGENERATE_INFOPLIST_FILE = YES;")
    pbx.append("\t\t\t\tMARKETING_VERSION = 1.0;")
    pbx.append("\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = com.tiktokcleaner.app.tests;")
    pbx.append("\t\t\t\tPRODUCT_NAME = \"$(TARGET_NAME)\";")
    pbx.append("\t\t\t\tSWIFT_VERSION = 5.0;")
    pbx.append("\t\t\t\tTARGETED_DEVICE_FAMILY = \"1,2\";")
    pbx.append("\t\t\t\tTEST_HOST = \"$(BUILT_PRODUCTS_DIR)/TikTokCleaner.app/TikTokCleaner\";")
    pbx.append("\t\t\t};")
    pbx.append("\t\t\tname = Debug;")
    pbx.append("\t\t};")
    
    pbx.append(f"\t\t{test_release_config_uuid} /* Release */ = {{")
    pbx.append("\t\t\tisa = XCBuildConfiguration;")
    pbx.append("\t\t\tbuildSettings = {")
    pbx.append("\t\t\t\tBUNDLE_LOADER = \"$(TEST_HOST)\";")
    pbx.append("\t\t\t\tCODE_SIGN_STYLE = Automatic;")
    pbx.append("\t\t\t\tCURRENT_PROJECT_VERSION = 1;")
    pbx.append("\t\t\t\tGENERATE_INFOPLIST_FILE = YES;")
    pbx.append("\t\t\t\tMARKETING_VERSION = 1.0;")
    pbx.append("\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = com.tiktokcleaner.app.tests;")
    pbx.append("\t\t\t\tPRODUCT_NAME = \"$(TARGET_NAME)\";")
    pbx.append("\t\t\t\tSWIFT_VERSION = 5.0;")
    pbx.append("\t\t\t\tTARGETED_DEVICE_FAMILY = \"1,2\";")
    pbx.append("\t\t\t\tTEST_HOST = \"$(BUILT_PRODUCTS_DIR)/TikTokCleaner.app/TikTokCleaner\";")
    pbx.append("\t\t\t};")
    pbx.append("\t\t\tname = Release;")
    pbx.append("\t\t};")
    pbx.append("/* End XCBuildConfiguration section */\n")
    
    # 12. XCConfigurationList
    pbx.append("/* Begin XCConfigurationList section */")
    pbx.append(f"\t\t{proj_config_list_uuid} /* Build configuration list for PBXProject \"TikTokCleaner\" */ = {{")
    pbx.append("\t\t\tisa = XCConfigurationList;")
    pbx.append("\t\t\tbuildConfigurations = (")
    pbx.append(f"\t\t\t\t{proj_debug_config_uuid} /* Debug */,")
    pbx.append(f"\t\t\t\t{proj_release_config_uuid} /* Release */,")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\tdefaultConfigurationIsVisible = 0;")
    pbx.append("\t\t\tdefaultConfigurationName = Release;")
    pbx.append("\t\t};")
    
    pbx.append(f"\t\t{app_config_list_uuid} /* Build configuration list for PBXNativeTarget \"TikTokCleaner\" */ = {{")
    pbx.append("\t\t\tisa = XCConfigurationList;")
    pbx.append("\t\t\tbuildConfigurations = (")
    pbx.append(f"\t\t\t\t{app_debug_config_uuid} /* Debug */,")
    pbx.append(f"\t\t\t\t{app_release_config_uuid} /* Release */,")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\tdefaultConfigurationIsVisible = 0;")
    pbx.append("\t\t\tdefaultConfigurationName = Release;")
    pbx.append("\t\t};")
    
    pbx.append(f"\t\t{test_config_list_uuid} /* Build configuration list for PBXNativeTarget \"TikTokCleanerTests\" */ = {{")
    pbx.append("\t\t\tisa = XCConfigurationList;")
    pbx.append("\t\t\tbuildConfigurations = (")
    pbx.append(f"\t\t\t\t{test_debug_config_uuid} /* Debug */,")
    pbx.append(f"\t\t\t\t{test_release_config_uuid} /* Release */,")
    pbx.append("\t\t\t);")
    pbx.append("\t\t\tdefaultConfigurationIsVisible = 0;")
    pbx.append("\t\t\tdefaultConfigurationName = Release;")
    pbx.append("\t\t};")
    pbx.append("/* End XCConfigurationList section */\n")
    
    pbx.append("\t};")
    pbx.append(f"\trootObject = {proj_uuid} /* Project object */;")
    pbx.append("}")
    
    target_path = os.path.join(proj_dir, "project.pbxproj")
    with open(target_path, "w", encoding="utf-8") as out:
        out.write("\n".join(pbx) + "\n")
    print(f"Generated {target_path} successfully ({len(all_files)} files referenced).")

if __name__ == "__main__":
    main()
